server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tFmWt9pHNQDNMzEngk6
    keySecret: MraJgpHBZm7DzkvaKgDmzNCzW26oUh
    bucketName: rzb-1111

