server:
  port: 8120 # 服务端口

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  #spring:
  rabbitmq:
    host: 192.168.253.129
    port: 5672
    virtual-host: /
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: #123456 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: 你的keyid
    key-secret: 你的keysecret
    template-code: 908e94ccf08b4476ba6c876d13f084ad
    sign-name: 你的短信模板签名


feign:
  #开启Feign对Sentinel的支持
  #feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置


logging:
  level:
    com.softeem.rzb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口